### ISSUE TITLE
Not sure FLASH_ALIGN used correctly in flashProgramWord & security bits mention...

### ISSUE THREAD

**Issue by robsoles** [FrankBoesing/Arduino-Teensy3-Flash#1]
using 3 as 'align' on line 101 of cpp file where I think it needs to be 4 to achieve the objective. Just fixing the write to a four byte boundary without correcting data may be problematic to less well informed users - it may be better to return with an error code (without writing to flash), if their address isn't already aligned, instead of just changing the destination.

I am working on the lock bits business, I'm setting bits (or, rather, unsetting) successfully, just a bit more experimentation in absolute minimum requirement to make it safe to try to re-program using the Teensy loader - pull request in less than 7 days, pretty sure.

**Comment by FrankBoesing** [comment]
Thank you !
